package com.hoperun.tms.bean.base;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class Carrier extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.CONTACT_PERSON
     *
     * @mbggenerated
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.CONTACT_TEL
     *
     * @mbggenerated
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.C_NO
     *
     * @mbggenerated
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_CARRIER.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.ID
     *
     * @return the value of MIR.TMS_CARRIER.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.ID
     *
     * @param id the value for MIR.TMS_CARRIER.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.NAME
     *
     * @return the value of MIR.TMS_CARRIER.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.NAME
     *
     * @param name the value for MIR.TMS_CARRIER.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.TYPE
     *
     * @return the value of MIR.TMS_CARRIER.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.TYPE
     *
     * @param type the value for MIR.TMS_CARRIER.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.CONTACT_PERSON
     *
     * @return the value of MIR.TMS_CARRIER.CONTACT_PERSON
     *
     * @mbggenerated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.CONTACT_PERSON
     *
     * @param contactPerson the value for MIR.TMS_CARRIER.CONTACT_PERSON
     *
     * @mbggenerated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.CONTACT_TEL
     *
     * @return the value of MIR.TMS_CARRIER.CONTACT_TEL
     *
     * @mbggenerated
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.CONTACT_TEL
     *
     * @param contactTel the value for MIR.TMS_CARRIER.CONTACT_TEL
     *
     * @mbggenerated
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.ADDRESS
     *
     * @return the value of MIR.TMS_CARRIER.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.ADDRESS
     *
     * @param address the value for MIR.TMS_CARRIER.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.C_NO
     *
     * @return the value of MIR.TMS_CARRIER.C_NO
     *
     * @mbggenerated
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.C_NO
     *
     * @param cNo the value for MIR.TMS_CARRIER.C_NO
     *
     * @mbggenerated
     */
    public void setcNo(String cNo) {
        this.cNo = cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.STATUS
     *
     * @return the value of MIR.TMS_CARRIER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.STATUS
     *
     * @param status the value for MIR.TMS_CARRIER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.CREATED_BY
     *
     * @return the value of MIR.TMS_CARRIER.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_CARRIER.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.CREATED_AT
     *
     * @return the value of MIR.TMS_CARRIER.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_CARRIER.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.UPDATED_BY
     *
     * @return the value of MIR.TMS_CARRIER.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_CARRIER.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_CARRIER.UPDATED_AT
     *
     * @return the value of MIR.TMS_CARRIER.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_CARRIER.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_CARRIER.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}