package com.hoperun.tms.bean.base;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class Driver extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.D_ID
     *
     * @mbggenerated
     */
    private String dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CONTACT
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CER_TYPE
     *
     * @mbggenerated
     */
    private String cerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CER_NO
     *
     * @mbggenerated
     */
    private String cerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CER_CAR_TYPE
     *
     * @mbggenerated
     */
    private String cerCarType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CER_EXPIRE_DATE
     *
     * @mbggenerated
     */
    private Date cerExpireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.WEBCHAT
     *
     * @mbggenerated
     */
    private String webchat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DRIVER.WX_OPEN_ID
     *
     * @mbggenerated
     */
    private String wxOpenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.ID
     *
     * @return the value of MIR.TMS_DRIVER.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.ID
     *
     * @param id the value for MIR.TMS_DRIVER.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.NAME
     *
     * @return the value of MIR.TMS_DRIVER.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.NAME
     *
     * @param name the value for MIR.TMS_DRIVER.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.D_ID
     *
     * @return the value of MIR.TMS_DRIVER.D_ID
     *
     * @mbggenerated
     */
    public String getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.D_ID
     *
     * @param dId the value for MIR.TMS_DRIVER.D_ID
     *
     * @mbggenerated
     */
    public void setdId(String dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CONTACT
     *
     * @return the value of MIR.TMS_DRIVER.CONTACT
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CONTACT
     *
     * @param contact the value for MIR.TMS_DRIVER.CONTACT
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CER_TYPE
     *
     * @return the value of MIR.TMS_DRIVER.CER_TYPE
     *
     * @mbggenerated
     */
    public String getCerType() {
        return cerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CER_TYPE
     *
     * @param cerType the value for MIR.TMS_DRIVER.CER_TYPE
     *
     * @mbggenerated
     */
    public void setCerType(String cerType) {
        this.cerType = cerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CER_NO
     *
     * @return the value of MIR.TMS_DRIVER.CER_NO
     *
     * @mbggenerated
     */
    public String getCerNo() {
        return cerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CER_NO
     *
     * @param cerNo the value for MIR.TMS_DRIVER.CER_NO
     *
     * @mbggenerated
     */
    public void setCerNo(String cerNo) {
        this.cerNo = cerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CER_CAR_TYPE
     *
     * @return the value of MIR.TMS_DRIVER.CER_CAR_TYPE
     *
     * @mbggenerated
     */
    public String getCerCarType() {
        return cerCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CER_CAR_TYPE
     *
     * @param cerCarType the value for MIR.TMS_DRIVER.CER_CAR_TYPE
     *
     * @mbggenerated
     */
    public void setCerCarType(String cerCarType) {
        this.cerCarType = cerCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CER_EXPIRE_DATE
     *
     * @return the value of MIR.TMS_DRIVER.CER_EXPIRE_DATE
     *
     * @mbggenerated
     */
    public Date getCerExpireDate() {
        return cerExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CER_EXPIRE_DATE
     *
     * @param cerExpireDate the value for MIR.TMS_DRIVER.CER_EXPIRE_DATE
     *
     * @mbggenerated
     */
    public void setCerExpireDate(Date cerExpireDate) {
        this.cerExpireDate = cerExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.SEX
     *
     * @return the value of MIR.TMS_DRIVER.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.SEX
     *
     * @param sex the value for MIR.TMS_DRIVER.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.WEBCHAT
     *
     * @return the value of MIR.TMS_DRIVER.WEBCHAT
     *
     * @mbggenerated
     */
    public String getWebchat() {
        return webchat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.WEBCHAT
     *
     * @param webchat the value for MIR.TMS_DRIVER.WEBCHAT
     *
     * @mbggenerated
     */
    public void setWebchat(String webchat) {
        this.webchat = webchat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.STATUS
     *
     * @return the value of MIR.TMS_DRIVER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.STATUS
     *
     * @param status the value for MIR.TMS_DRIVER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CREATED_BY
     *
     * @return the value of MIR.TMS_DRIVER.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_DRIVER.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.CREATED_AT
     *
     * @return the value of MIR.TMS_DRIVER.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_DRIVER.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.UPDATED_BY
     *
     * @return the value of MIR.TMS_DRIVER.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_DRIVER.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.UPDATED_AT
     *
     * @return the value of MIR.TMS_DRIVER.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_DRIVER.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DRIVER.WX_OPEN_ID
     *
     * @return the value of MIR.TMS_DRIVER.WX_OPEN_ID
     *
     * @mbggenerated
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DRIVER.WX_OPEN_ID
     *
     * @param wxOpenId the value for MIR.TMS_DRIVER.WX_OPEN_ID
     *
     * @mbggenerated
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId;
    }
}