package com.hoperun.tms.bean.base;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class Route extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.TERMINATION
     *
     * @mbggenerated
     */
    private String termination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.AREA
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_ROUTE.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.ID
     *
     * @return the value of MIR.TMS_ROUTE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.ID
     *
     * @param id the value for MIR.TMS_ROUTE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.NAME
     *
     * @return the value of MIR.TMS_ROUTE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.NAME
     *
     * @param name the value for MIR.TMS_ROUTE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.TERMINATION
     *
     * @return the value of MIR.TMS_ROUTE.TERMINATION
     *
     * @mbggenerated
     */
    public String getTermination() {
        return termination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.TERMINATION
     *
     * @param termination the value for MIR.TMS_ROUTE.TERMINATION
     *
     * @mbggenerated
     */
    public void setTermination(String termination) {
        this.termination = termination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.CITY
     *
     * @return the value of MIR.TMS_ROUTE.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.CITY
     *
     * @param city the value for MIR.TMS_ROUTE.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.AREA
     *
     * @return the value of MIR.TMS_ROUTE.AREA
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.AREA
     *
     * @param area the value for MIR.TMS_ROUTE.AREA
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.REMARK
     *
     * @return the value of MIR.TMS_ROUTE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.REMARK
     *
     * @param remark the value for MIR.TMS_ROUTE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.STATUS
     *
     * @return the value of MIR.TMS_ROUTE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.STATUS
     *
     * @param status the value for MIR.TMS_ROUTE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.CREATED_BY
     *
     * @return the value of MIR.TMS_ROUTE.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_ROUTE.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.CREATED_AT
     *
     * @return the value of MIR.TMS_ROUTE.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_ROUTE.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.UPDATED_BY
     *
     * @return the value of MIR.TMS_ROUTE.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_ROUTE.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_ROUTE.UPDATED_AT
     *
     * @return the value of MIR.TMS_ROUTE.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_ROUTE.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_ROUTE.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}