package com.hoperun.tms.bean.base;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class VehicleDriver extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.V_ID
     *
     * @mbggenerated
     */
    private Long vId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.D_ID
     *
     * @mbggenerated
     */
    private Long dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.V_NO
     *
     * @mbggenerated
     */
    private String vNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE_DRIVER.D_NAME
     *
     * @mbggenerated
     */
    private String dName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.ID
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.ID
     *
     * @param id the value for MIR.TMS_VEHICLE_DRIVER.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.V_ID
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.V_ID
     *
     * @mbggenerated
     */
    public Long getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.V_ID
     *
     * @param vId the value for MIR.TMS_VEHICLE_DRIVER.V_ID
     *
     * @mbggenerated
     */
    public void setvId(Long vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.D_ID
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.D_ID
     *
     * @mbggenerated
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.D_ID
     *
     * @param dId the value for MIR.TMS_VEHICLE_DRIVER.D_ID
     *
     * @mbggenerated
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.STATUS
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.STATUS
     *
     * @param status the value for MIR.TMS_VEHICLE_DRIVER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.CREATED_BY
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_VEHICLE_DRIVER.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.CREATED_AT
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_VEHICLE_DRIVER.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.UPDATED_BY
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_VEHICLE_DRIVER.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.UPDATED_AT
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_VEHICLE_DRIVER.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.V_NO
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.V_NO
     *
     * @mbggenerated
     */
    public String getvNo() {
        return vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.V_NO
     *
     * @param vNo the value for MIR.TMS_VEHICLE_DRIVER.V_NO
     *
     * @mbggenerated
     */
    public void setvNo(String vNo) {
        this.vNo = vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE_DRIVER.D_NAME
     *
     * @return the value of MIR.TMS_VEHICLE_DRIVER.D_NAME
     *
     * @mbggenerated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE_DRIVER.D_NAME
     *
     * @param dName the value for MIR.TMS_VEHICLE_DRIVER.D_NAME
     *
     * @mbggenerated
     */
    public void setdName(String dName) {
        this.dName = dName;
    }
}