package com.hoperun.tms.bean.base;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class Vehicle extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.V_NO
     *
     * @mbggenerated
     */
    private String vNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.REG_DATE
     *
     * @mbggenerated
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.V_TYPE
     *
     * @mbggenerated
     */
    private String vType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.DRIVER_TYPE
     *
     * @mbggenerated
     */
    private String driverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.V_WEIGHT
     *
     * @mbggenerated
     */
    private Long vWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.V_SIZE
     *
     * @mbggenerated
     */
    private Long vSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.DELIVERY_TYPE
     *
     * @mbggenerated
     */
    private String deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_VEHICLE.NO
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.ID
     *
     * @return the value of MIR.TMS_VEHICLE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.ID
     *
     * @param id the value for MIR.TMS_VEHICLE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.V_NO
     *
     * @return the value of MIR.TMS_VEHICLE.V_NO
     *
     * @mbggenerated
     */
    public String getvNo() {
        return vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.V_NO
     *
     * @param vNo the value for MIR.TMS_VEHICLE.V_NO
     *
     * @mbggenerated
     */
    public void setvNo(String vNo) {
        this.vNo = vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.REG_DATE
     *
     * @return the value of MIR.TMS_VEHICLE.REG_DATE
     *
     * @mbggenerated
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.REG_DATE
     *
     * @param regDate the value for MIR.TMS_VEHICLE.REG_DATE
     *
     * @mbggenerated
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.V_TYPE
     *
     * @return the value of MIR.TMS_VEHICLE.V_TYPE
     *
     * @mbggenerated
     */
    public String getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.V_TYPE
     *
     * @param vType the value for MIR.TMS_VEHICLE.V_TYPE
     *
     * @mbggenerated
     */
    public void setvType(String vType) {
        this.vType = vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.DRIVER_TYPE
     *
     * @return the value of MIR.TMS_VEHICLE.DRIVER_TYPE
     *
     * @mbggenerated
     */
    public String getDriverType() {
        return driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.DRIVER_TYPE
     *
     * @param driverType the value for MIR.TMS_VEHICLE.DRIVER_TYPE
     *
     * @mbggenerated
     */
    public void setDriverType(String driverType) {
        this.driverType = driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.V_WEIGHT
     *
     * @return the value of MIR.TMS_VEHICLE.V_WEIGHT
     *
     * @mbggenerated
     */
    public Long getvWeight() {
        return vWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.V_WEIGHT
     *
     * @param vWeight the value for MIR.TMS_VEHICLE.V_WEIGHT
     *
     * @mbggenerated
     */
    public void setvWeight(Long vWeight) {
        this.vWeight = vWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.V_SIZE
     *
     * @return the value of MIR.TMS_VEHICLE.V_SIZE
     *
     * @mbggenerated
     */
    public Long getvSize() {
        return vSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.V_SIZE
     *
     * @param vSize the value for MIR.TMS_VEHICLE.V_SIZE
     *
     * @mbggenerated
     */
    public void setvSize(Long vSize) {
        this.vSize = vSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.DELIVERY_TYPE
     *
     * @return the value of MIR.TMS_VEHICLE.DELIVERY_TYPE
     *
     * @mbggenerated
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.DELIVERY_TYPE
     *
     * @param deliveryType the value for MIR.TMS_VEHICLE.DELIVERY_TYPE
     *
     * @mbggenerated
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.REMARK
     *
     * @return the value of MIR.TMS_VEHICLE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.REMARK
     *
     * @param remark the value for MIR.TMS_VEHICLE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.STATUS
     *
     * @return the value of MIR.TMS_VEHICLE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.STATUS
     *
     * @param status the value for MIR.TMS_VEHICLE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.CREATED_BY
     *
     * @return the value of MIR.TMS_VEHICLE.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_VEHICLE.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.CREATED_AT
     *
     * @return the value of MIR.TMS_VEHICLE.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_VEHICLE.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.UPDATED_BY
     *
     * @return the value of MIR.TMS_VEHICLE.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_VEHICLE.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.UPDATED_AT
     *
     * @return the value of MIR.TMS_VEHICLE.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_VEHICLE.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_VEHICLE.NO
     *
     * @return the value of MIR.TMS_VEHICLE.NO
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_VEHICLE.NO
     *
     * @param no the value for MIR.TMS_VEHICLE.NO
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no;
    }
}