package com.hoperun.tms.bean.customer;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class DeliveryBillTmp extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.D_ID
     *
     * @mbggenerated
     */
    private Long dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.D_NAME
     *
     * @mbggenerated
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.D_MOBILE
     *
     * @mbggenerated
     */
    private String dMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL_TMP.W_NO
     *
     * @mbggenerated
     */
    private String wNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.ID
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.ID
     *
     * @param id the value for MIR.TMS_DELIVERY_BILL_TMP.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.D_ID
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.D_ID
     *
     * @mbggenerated
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.D_ID
     *
     * @param dId the value for MIR.TMS_DELIVERY_BILL_TMP.D_ID
     *
     * @mbggenerated
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.D_NAME
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.D_NAME
     *
     * @mbggenerated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.D_NAME
     *
     * @param dName the value for MIR.TMS_DELIVERY_BILL_TMP.D_NAME
     *
     * @mbggenerated
     */
    public void setdName(String dName) {
        this.dName = dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.STATUS
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.STATUS
     *
     * @param status the value for MIR.TMS_DELIVERY_BILL_TMP.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.CREATED_BY
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_DELIVERY_BILL_TMP.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.CREATED_AT
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_DELIVERY_BILL_TMP.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.UPDATED_BY
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_DELIVERY_BILL_TMP.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.UPDATED_AT
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_DELIVERY_BILL_TMP.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.D_MOBILE
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.D_MOBILE
     *
     * @mbggenerated
     */
    public String getdMobile() {
        return dMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.D_MOBILE
     *
     * @param dMobile the value for MIR.TMS_DELIVERY_BILL_TMP.D_MOBILE
     *
     * @mbggenerated
     */
    public void setdMobile(String dMobile) {
        this.dMobile = dMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL_TMP.W_NO
     *
     * @return the value of MIR.TMS_DELIVERY_BILL_TMP.W_NO
     *
     * @mbggenerated
     */
    public String getwNo() {
        return wNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL_TMP.W_NO
     *
     * @param wNo the value for MIR.TMS_DELIVERY_BILL_TMP.W_NO
     *
     * @mbggenerated
     */
    public void setwNo(String wNo) {
        this.wNo = wNo;
    }
}