package com.hoperun.tms.bean.customer;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class DeliveryBill extends BaseBean {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.NO
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.V_ID
     *
     * @mbggenerated
     */
    private Long vId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.V_NO
     *
     * @mbggenerated
     */
    private String vNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.D_ID
     *
     * @mbggenerated
     */
    private Long dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.D_NAME
     *
     * @mbggenerated
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.DELIVERY_ORIGIN
     *
     * @mbggenerated
     */
    private String deliveryOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.DELIVERY_TERM
     *
     * @mbggenerated
     */
    private String deliveryTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.R_ID
     *
     * @mbggenerated
     */
    private Long rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.R_NAME
     *
     * @mbggenerated
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.R_TERM
     *
     * @mbggenerated
     */
    private String rTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_DELIVERY_BILL.ARRIVE_BY
     *
     * @mbggenerated
     */
    private Date arriveBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.ID
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.ID
     *
     * @param id the value for MIR.TMS_DELIVERY_BILL.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.NO
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.NO
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.NO
     *
     * @param no the value for MIR.TMS_DELIVERY_BILL.NO
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.V_ID
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.V_ID
     *
     * @mbggenerated
     */
    public Long getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.V_ID
     *
     * @param vId the value for MIR.TMS_DELIVERY_BILL.V_ID
     *
     * @mbggenerated
     */
    public void setvId(Long vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.V_NO
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.V_NO
     *
     * @mbggenerated
     */
    public String getvNo() {
        return vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.V_NO
     *
     * @param vNo the value for MIR.TMS_DELIVERY_BILL.V_NO
     *
     * @mbggenerated
     */
    public void setvNo(String vNo) {
        this.vNo = vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.D_ID
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.D_ID
     *
     * @mbggenerated
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.D_ID
     *
     * @param dId the value for MIR.TMS_DELIVERY_BILL.D_ID
     *
     * @mbggenerated
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.D_NAME
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.D_NAME
     *
     * @mbggenerated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.D_NAME
     *
     * @param dName the value for MIR.TMS_DELIVERY_BILL.D_NAME
     *
     * @mbggenerated
     */
    public void setdName(String dName) {
        this.dName = dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.DELIVERY_ORIGIN
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.DELIVERY_ORIGIN
     *
     * @mbggenerated
     */
    public String getDeliveryOrigin() {
        return deliveryOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.DELIVERY_ORIGIN
     *
     * @param deliveryOrigin the value for MIR.TMS_DELIVERY_BILL.DELIVERY_ORIGIN
     *
     * @mbggenerated
     */
    public void setDeliveryOrigin(String deliveryOrigin) {
        this.deliveryOrigin = deliveryOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.DELIVERY_TERM
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.DELIVERY_TERM
     *
     * @mbggenerated
     */
    public String getDeliveryTerm() {
        return deliveryTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.DELIVERY_TERM
     *
     * @param deliveryTerm the value for MIR.TMS_DELIVERY_BILL.DELIVERY_TERM
     *
     * @mbggenerated
     */
    public void setDeliveryTerm(String deliveryTerm) {
        this.deliveryTerm = deliveryTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.STATUS
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.STATUS
     *
     * @param status the value for MIR.TMS_DELIVERY_BILL.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.CREATED_BY
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_DELIVERY_BILL.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.CREATED_AT
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_DELIVERY_BILL.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.UPDATED_BY
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_DELIVERY_BILL.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.UPDATED_AT
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_DELIVERY_BILL.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.R_ID
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.R_ID
     *
     * @mbggenerated
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.R_ID
     *
     * @param rId the value for MIR.TMS_DELIVERY_BILL.R_ID
     *
     * @mbggenerated
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.R_NAME
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.R_NAME
     *
     * @mbggenerated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.R_NAME
     *
     * @param rName the value for MIR.TMS_DELIVERY_BILL.R_NAME
     *
     * @mbggenerated
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.R_TERM
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.R_TERM
     *
     * @mbggenerated
     */
    public String getrTerm() {
        return rTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.R_TERM
     *
     * @param rTerm the value for MIR.TMS_DELIVERY_BILL.R_TERM
     *
     * @mbggenerated
     */
    public void setrTerm(String rTerm) {
        this.rTerm = rTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_DELIVERY_BILL.ARRIVE_BY
     *
     * @return the value of MIR.TMS_DELIVERY_BILL.ARRIVE_BY
     *
     * @mbggenerated
     */
    public Date getArriveBy() {
        return arriveBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_DELIVERY_BILL.ARRIVE_BY
     *
     * @param arriveBy the value for MIR.TMS_DELIVERY_BILL.ARRIVE_BY
     *
     * @mbggenerated
     */
    public void setArriveBy(Date arriveBy) {
        this.arriveBy = arriveBy;
    }
}