package com.hoperun.tms.bean.customer;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeliveryBillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public DeliveryBillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoIsNull() {
            addCriterion("NO is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("NO is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("NO =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("NO <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("NO >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("NO >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("NO <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("NO <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("NO like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("NO not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("NO in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("NO not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("NO between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("NO not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andVIdIsNull() {
            addCriterion("V_ID is null");
            return (Criteria) this;
        }

        public Criteria andVIdIsNotNull() {
            addCriterion("V_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVIdEqualTo(Long value) {
            addCriterion("V_ID =", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotEqualTo(Long value) {
            addCriterion("V_ID <>", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdGreaterThan(Long value) {
            addCriterion("V_ID >", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdGreaterThanOrEqualTo(Long value) {
            addCriterion("V_ID >=", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLessThan(Long value) {
            addCriterion("V_ID <", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdLessThanOrEqualTo(Long value) {
            addCriterion("V_ID <=", value, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdIn(List<Long> values) {
            addCriterion("V_ID in", values, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotIn(List<Long> values) {
            addCriterion("V_ID not in", values, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdBetween(Long value1, Long value2) {
            addCriterion("V_ID between", value1, value2, "vId");
            return (Criteria) this;
        }

        public Criteria andVIdNotBetween(Long value1, Long value2) {
            addCriterion("V_ID not between", value1, value2, "vId");
            return (Criteria) this;
        }

        public Criteria andVNoIsNull() {
            addCriterion("V_NO is null");
            return (Criteria) this;
        }

        public Criteria andVNoIsNotNull() {
            addCriterion("V_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVNoEqualTo(String value) {
            addCriterion("V_NO =", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoNotEqualTo(String value) {
            addCriterion("V_NO <>", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoGreaterThan(String value) {
            addCriterion("V_NO >", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoGreaterThanOrEqualTo(String value) {
            addCriterion("V_NO >=", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoLessThan(String value) {
            addCriterion("V_NO <", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoLessThanOrEqualTo(String value) {
            addCriterion("V_NO <=", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoLike(String value) {
            addCriterion("V_NO like", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoNotLike(String value) {
            addCriterion("V_NO not like", value, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoIn(List<String> values) {
            addCriterion("V_NO in", values, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoNotIn(List<String> values) {
            addCriterion("V_NO not in", values, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoBetween(String value1, String value2) {
            addCriterion("V_NO between", value1, value2, "vNo");
            return (Criteria) this;
        }

        public Criteria andVNoNotBetween(String value1, String value2) {
            addCriterion("V_NO not between", value1, value2, "vNo");
            return (Criteria) this;
        }

        public Criteria andDIdIsNull() {
            addCriterion("D_ID is null");
            return (Criteria) this;
        }

        public Criteria andDIdIsNotNull() {
            addCriterion("D_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDIdEqualTo(Long value) {
            addCriterion("D_ID =", value, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdNotEqualTo(Long value) {
            addCriterion("D_ID <>", value, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdGreaterThan(Long value) {
            addCriterion("D_ID >", value, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdGreaterThanOrEqualTo(Long value) {
            addCriterion("D_ID >=", value, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdLessThan(Long value) {
            addCriterion("D_ID <", value, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdLessThanOrEqualTo(Long value) {
            addCriterion("D_ID <=", value, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdIn(List<Long> values) {
            addCriterion("D_ID in", values, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdNotIn(List<Long> values) {
            addCriterion("D_ID not in", values, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdBetween(Long value1, Long value2) {
            addCriterion("D_ID between", value1, value2, "dId");
            return (Criteria) this;
        }

        public Criteria andDIdNotBetween(Long value1, Long value2) {
            addCriterion("D_ID not between", value1, value2, "dId");
            return (Criteria) this;
        }

        public Criteria andDNameIsNull() {
            addCriterion("D_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDNameIsNotNull() {
            addCriterion("D_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDNameEqualTo(String value) {
            addCriterion("D_NAME =", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameNotEqualTo(String value) {
            addCriterion("D_NAME <>", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameGreaterThan(String value) {
            addCriterion("D_NAME >", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameGreaterThanOrEqualTo(String value) {
            addCriterion("D_NAME >=", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameLessThan(String value) {
            addCriterion("D_NAME <", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameLessThanOrEqualTo(String value) {
            addCriterion("D_NAME <=", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameLike(String value) {
            addCriterion("D_NAME like", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameNotLike(String value) {
            addCriterion("D_NAME not like", value, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameIn(List<String> values) {
            addCriterion("D_NAME in", values, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameNotIn(List<String> values) {
            addCriterion("D_NAME not in", values, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameBetween(String value1, String value2) {
            addCriterion("D_NAME between", value1, value2, "dName");
            return (Criteria) this;
        }

        public Criteria andDNameNotBetween(String value1, String value2) {
            addCriterion("D_NAME not between", value1, value2, "dName");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginIsNull() {
            addCriterion("DELIVERY_ORIGIN is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginIsNotNull() {
            addCriterion("DELIVERY_ORIGIN is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginEqualTo(String value) {
            addCriterion("DELIVERY_ORIGIN =", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginNotEqualTo(String value) {
            addCriterion("DELIVERY_ORIGIN <>", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginGreaterThan(String value) {
            addCriterion("DELIVERY_ORIGIN >", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ORIGIN >=", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginLessThan(String value) {
            addCriterion("DELIVERY_ORIGIN <", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_ORIGIN <=", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginLike(String value) {
            addCriterion("DELIVERY_ORIGIN like", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginNotLike(String value) {
            addCriterion("DELIVERY_ORIGIN not like", value, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginIn(List<String> values) {
            addCriterion("DELIVERY_ORIGIN in", values, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginNotIn(List<String> values) {
            addCriterion("DELIVERY_ORIGIN not in", values, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginBetween(String value1, String value2) {
            addCriterion("DELIVERY_ORIGIN between", value1, value2, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryOriginNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_ORIGIN not between", value1, value2, "deliveryOrigin");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermIsNull() {
            addCriterion("DELIVERY_TERM is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermIsNotNull() {
            addCriterion("DELIVERY_TERM is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermEqualTo(String value) {
            addCriterion("DELIVERY_TERM =", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermNotEqualTo(String value) {
            addCriterion("DELIVERY_TERM <>", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermGreaterThan(String value) {
            addCriterion("DELIVERY_TERM >", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_TERM >=", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermLessThan(String value) {
            addCriterion("DELIVERY_TERM <", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_TERM <=", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermLike(String value) {
            addCriterion("DELIVERY_TERM like", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermNotLike(String value) {
            addCriterion("DELIVERY_TERM not like", value, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermIn(List<String> values) {
            addCriterion("DELIVERY_TERM in", values, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermNotIn(List<String> values) {
            addCriterion("DELIVERY_TERM not in", values, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermBetween(String value1, String value2) {
            addCriterion("DELIVERY_TERM between", value1, value2, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andDeliveryTermNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_TERM not between", value1, value2, "deliveryTerm");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("CREATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("CREATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("CREATED_AT =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("CREATED_AT <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("CREATED_AT >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("CREATED_AT <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("CREATED_AT in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("CREATED_AT not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("UPDATED_BY =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("UPDATED_BY <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("UPDATED_BY >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATED_BY >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("UPDATED_BY <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("UPDATED_BY <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("UPDATED_BY like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("UPDATED_BY not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("UPDATED_BY in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("UPDATED_BY not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("UPDATED_BY between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("UPDATED_BY not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("UPDATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("UPDATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("UPDATED_AT =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("UPDATED_AT <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("UPDATED_AT >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("UPDATED_AT <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("UPDATED_AT in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("UPDATED_AT not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andRIdIsNull() {
            addCriterion("R_ID is null");
            return (Criteria) this;
        }

        public Criteria andRIdIsNotNull() {
            addCriterion("R_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRIdEqualTo(Long value) {
            addCriterion("R_ID =", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotEqualTo(Long value) {
            addCriterion("R_ID <>", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThan(Long value) {
            addCriterion("R_ID >", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThanOrEqualTo(Long value) {
            addCriterion("R_ID >=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThan(Long value) {
            addCriterion("R_ID <", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThanOrEqualTo(Long value) {
            addCriterion("R_ID <=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdIn(List<Long> values) {
            addCriterion("R_ID in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotIn(List<Long> values) {
            addCriterion("R_ID not in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdBetween(Long value1, Long value2) {
            addCriterion("R_ID between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotBetween(Long value1, Long value2) {
            addCriterion("R_ID not between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andRNameIsNull() {
            addCriterion("R_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRNameIsNotNull() {
            addCriterion("R_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRNameEqualTo(String value) {
            addCriterion("R_NAME =", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotEqualTo(String value) {
            addCriterion("R_NAME <>", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThan(String value) {
            addCriterion("R_NAME >", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThanOrEqualTo(String value) {
            addCriterion("R_NAME >=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThan(String value) {
            addCriterion("R_NAME <", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThanOrEqualTo(String value) {
            addCriterion("R_NAME <=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLike(String value) {
            addCriterion("R_NAME like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotLike(String value) {
            addCriterion("R_NAME not like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameIn(List<String> values) {
            addCriterion("R_NAME in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotIn(List<String> values) {
            addCriterion("R_NAME not in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameBetween(String value1, String value2) {
            addCriterion("R_NAME between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotBetween(String value1, String value2) {
            addCriterion("R_NAME not between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRTermIsNull() {
            addCriterion("R_TERM is null");
            return (Criteria) this;
        }

        public Criteria andRTermIsNotNull() {
            addCriterion("R_TERM is not null");
            return (Criteria) this;
        }

        public Criteria andRTermEqualTo(String value) {
            addCriterion("R_TERM =", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermNotEqualTo(String value) {
            addCriterion("R_TERM <>", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermGreaterThan(String value) {
            addCriterion("R_TERM >", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermGreaterThanOrEqualTo(String value) {
            addCriterion("R_TERM >=", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermLessThan(String value) {
            addCriterion("R_TERM <", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermLessThanOrEqualTo(String value) {
            addCriterion("R_TERM <=", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermLike(String value) {
            addCriterion("R_TERM like", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermNotLike(String value) {
            addCriterion("R_TERM not like", value, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermIn(List<String> values) {
            addCriterion("R_TERM in", values, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermNotIn(List<String> values) {
            addCriterion("R_TERM not in", values, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermBetween(String value1, String value2) {
            addCriterion("R_TERM between", value1, value2, "rTerm");
            return (Criteria) this;
        }

        public Criteria andRTermNotBetween(String value1, String value2) {
            addCriterion("R_TERM not between", value1, value2, "rTerm");
            return (Criteria) this;
        }

        public Criteria andArriveByIsNull() {
            addCriterion("ARRIVE_BY is null");
            return (Criteria) this;
        }

        public Criteria andArriveByIsNotNull() {
            addCriterion("ARRIVE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andArriveByEqualTo(Date value) {
            addCriterion("ARRIVE_BY =", value, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByNotEqualTo(Date value) {
            addCriterion("ARRIVE_BY <>", value, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByGreaterThan(Date value) {
            addCriterion("ARRIVE_BY >", value, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByGreaterThanOrEqualTo(Date value) {
            addCriterion("ARRIVE_BY >=", value, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByLessThan(Date value) {
            addCriterion("ARRIVE_BY <", value, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByLessThanOrEqualTo(Date value) {
            addCriterion("ARRIVE_BY <=", value, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByIn(List<Date> values) {
            addCriterion("ARRIVE_BY in", values, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByNotIn(List<Date> values) {
            addCriterion("ARRIVE_BY not in", values, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByBetween(Date value1, Date value2) {
            addCriterion("ARRIVE_BY between", value1, value2, "arriveBy");
            return (Criteria) this;
        }

        public Criteria andArriveByNotBetween(Date value1, Date value2) {
            addCriterion("ARRIVE_BY not between", value1, value2, "arriveBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MIR.TMS_DELIVERY_BILL
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}