package com.hoperun.tms.bean.customer;

import com.hoperun.framework.base.BaseBean;
import java.util.Date;

public class WaybillLog extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.W_ID
     *
     * @mbggenerated
     */
    private Long wId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.W_NO
     *
     * @mbggenerated
     */
    private String wNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.W_LOG
     *
     * @mbggenerated
     */
    private String wLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL_LOG.W_STATUS
     *
     * @mbggenerated
     */
    private String wStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.ID
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.ID
     *
     * @param id the value for MIR.TMS_WAYBILL_LOG.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.W_ID
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.W_ID
     *
     * @mbggenerated
     */
    public Long getwId() {
        return wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.W_ID
     *
     * @param wId the value for MIR.TMS_WAYBILL_LOG.W_ID
     *
     * @mbggenerated
     */
    public void setwId(Long wId) {
        this.wId = wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.W_NO
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.W_NO
     *
     * @mbggenerated
     */
    public String getwNo() {
        return wNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.W_NO
     *
     * @param wNo the value for MIR.TMS_WAYBILL_LOG.W_NO
     *
     * @mbggenerated
     */
    public void setwNo(String wNo) {
        this.wNo = wNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.W_LOG
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.W_LOG
     *
     * @mbggenerated
     */
    public String getwLog() {
        return wLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.W_LOG
     *
     * @param wLog the value for MIR.TMS_WAYBILL_LOG.W_LOG
     *
     * @mbggenerated
     */
    public void setwLog(String wLog) {
        this.wLog = wLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.STATUS
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.STATUS
     *
     * @param status the value for MIR.TMS_WAYBILL_LOG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.CREATED_BY
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_WAYBILL_LOG.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.CREATED_AT
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_WAYBILL_LOG.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.UPDATED_BY
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_WAYBILL_LOG.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.UPDATED_AT
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_WAYBILL_LOG.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL_LOG.W_STATUS
     *
     * @return the value of MIR.TMS_WAYBILL_LOG.W_STATUS
     *
     * @mbggenerated
     */
    public String getwStatus() {
        return wStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL_LOG.W_STATUS
     *
     * @param wStatus the value for MIR.TMS_WAYBILL_LOG.W_STATUS
     *
     * @mbggenerated
     */
    public void setwStatus(String wStatus) {
        this.wStatus = wStatus;
    }
}