package com.hoperun.tms.bean.customer;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WaybillLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public WaybillLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWIdIsNull() {
            addCriterion("W_ID is null");
            return (Criteria) this;
        }

        public Criteria andWIdIsNotNull() {
            addCriterion("W_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWIdEqualTo(Long value) {
            addCriterion("W_ID =", value, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdNotEqualTo(Long value) {
            addCriterion("W_ID <>", value, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdGreaterThan(Long value) {
            addCriterion("W_ID >", value, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdGreaterThanOrEqualTo(Long value) {
            addCriterion("W_ID >=", value, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdLessThan(Long value) {
            addCriterion("W_ID <", value, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdLessThanOrEqualTo(Long value) {
            addCriterion("W_ID <=", value, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdIn(List<Long> values) {
            addCriterion("W_ID in", values, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdNotIn(List<Long> values) {
            addCriterion("W_ID not in", values, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdBetween(Long value1, Long value2) {
            addCriterion("W_ID between", value1, value2, "wId");
            return (Criteria) this;
        }

        public Criteria andWIdNotBetween(Long value1, Long value2) {
            addCriterion("W_ID not between", value1, value2, "wId");
            return (Criteria) this;
        }

        public Criteria andWNoIsNull() {
            addCriterion("W_NO is null");
            return (Criteria) this;
        }

        public Criteria andWNoIsNotNull() {
            addCriterion("W_NO is not null");
            return (Criteria) this;
        }

        public Criteria andWNoEqualTo(String value) {
            addCriterion("W_NO =", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoNotEqualTo(String value) {
            addCriterion("W_NO <>", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoGreaterThan(String value) {
            addCriterion("W_NO >", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoGreaterThanOrEqualTo(String value) {
            addCriterion("W_NO >=", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoLessThan(String value) {
            addCriterion("W_NO <", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoLessThanOrEqualTo(String value) {
            addCriterion("W_NO <=", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoLike(String value) {
            addCriterion("W_NO like", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoNotLike(String value) {
            addCriterion("W_NO not like", value, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoIn(List<String> values) {
            addCriterion("W_NO in", values, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoNotIn(List<String> values) {
            addCriterion("W_NO not in", values, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoBetween(String value1, String value2) {
            addCriterion("W_NO between", value1, value2, "wNo");
            return (Criteria) this;
        }

        public Criteria andWNoNotBetween(String value1, String value2) {
            addCriterion("W_NO not between", value1, value2, "wNo");
            return (Criteria) this;
        }

        public Criteria andWLogIsNull() {
            addCriterion("W_LOG is null");
            return (Criteria) this;
        }

        public Criteria andWLogIsNotNull() {
            addCriterion("W_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andWLogEqualTo(String value) {
            addCriterion("W_LOG =", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogNotEqualTo(String value) {
            addCriterion("W_LOG <>", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogGreaterThan(String value) {
            addCriterion("W_LOG >", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogGreaterThanOrEqualTo(String value) {
            addCriterion("W_LOG >=", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogLessThan(String value) {
            addCriterion("W_LOG <", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogLessThanOrEqualTo(String value) {
            addCriterion("W_LOG <=", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogLike(String value) {
            addCriterion("W_LOG like", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogNotLike(String value) {
            addCriterion("W_LOG not like", value, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogIn(List<String> values) {
            addCriterion("W_LOG in", values, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogNotIn(List<String> values) {
            addCriterion("W_LOG not in", values, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogBetween(String value1, String value2) {
            addCriterion("W_LOG between", value1, value2, "wLog");
            return (Criteria) this;
        }

        public Criteria andWLogNotBetween(String value1, String value2) {
            addCriterion("W_LOG not between", value1, value2, "wLog");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("CREATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("CREATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("CREATED_AT =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("CREATED_AT <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("CREATED_AT >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("CREATED_AT <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("CREATED_AT in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("CREATED_AT not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("UPDATED_BY =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("UPDATED_BY <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("UPDATED_BY >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATED_BY >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("UPDATED_BY <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("UPDATED_BY <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("UPDATED_BY like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("UPDATED_BY not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("UPDATED_BY in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("UPDATED_BY not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("UPDATED_BY between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("UPDATED_BY not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("UPDATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("UPDATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("UPDATED_AT =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("UPDATED_AT <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("UPDATED_AT >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("UPDATED_AT <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("UPDATED_AT in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("UPDATED_AT not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andWStatusIsNull() {
            addCriterion("W_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andWStatusIsNotNull() {
            addCriterion("W_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andWStatusEqualTo(String value) {
            addCriterion("W_STATUS =", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusNotEqualTo(String value) {
            addCriterion("W_STATUS <>", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusGreaterThan(String value) {
            addCriterion("W_STATUS >", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusGreaterThanOrEqualTo(String value) {
            addCriterion("W_STATUS >=", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusLessThan(String value) {
            addCriterion("W_STATUS <", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusLessThanOrEqualTo(String value) {
            addCriterion("W_STATUS <=", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusLike(String value) {
            addCriterion("W_STATUS like", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusNotLike(String value) {
            addCriterion("W_STATUS not like", value, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusIn(List<String> values) {
            addCriterion("W_STATUS in", values, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusNotIn(List<String> values) {
            addCriterion("W_STATUS not in", values, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusBetween(String value1, String value2) {
            addCriterion("W_STATUS between", value1, value2, "wStatus");
            return (Criteria) this;
        }

        public Criteria andWStatusNotBetween(String value1, String value2) {
            addCriterion("W_STATUS not between", value1, value2, "wStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MIR.TMS_WAYBILL_LOG
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}