package com.hoperun.tms.bean.customer;

import com.hoperun.framework.base.BaseBean;
import java.math.BigDecimal;
import java.util.Date;

public class Waybill extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.NO
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.TICKET_NO
     *
     * @mbggenerated
     */
    private String ticketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.SOURCE
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.RECIPIENT
     *
     * @mbggenerated
     */
    private String recipient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.RECEIVE_AT
     *
     * @mbggenerated
     */
    private Date receiveAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DELIVERY_TYPE
     *
     * @mbggenerated
     */
    private String deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DELIVERY_DATE
     *
     * @mbggenerated
     */
    private Date deliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DELIVERY_TIME
     *
     * @mbggenerated
     */
    private String deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_ID
     *
     * @mbggenerated
     */
    private Long dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_NAME
     *
     * @mbggenerated
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_CITY
     *
     * @mbggenerated
     */
    private String dCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_AREA
     *
     * @mbggenerated
     */
    private String dArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_POINT
     *
     * @mbggenerated
     */
    private String dPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_TEL
     *
     * @mbggenerated
     */
    private String dTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_CONTACT
     *
     * @mbggenerated
     */
    private String dContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_ADDRESS
     *
     * @mbggenerated
     */
    private String dAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_ID
     *
     * @mbggenerated
     */
    private Long rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_NAME
     *
     * @mbggenerated
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_CITY
     *
     * @mbggenerated
     */
    private String rCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_AREA
     *
     * @mbggenerated
     */
    private String rArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_TEL
     *
     * @mbggenerated
     */
    private String rTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_CONTACT
     *
     * @mbggenerated
     */
    private String rContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_ADDRESS
     *
     * @mbggenerated
     */
    private String rAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DETAIL_NAME
     *
     * @mbggenerated
     */
    private String detailName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DETAIL_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal detailWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DETAIL_SIZE
     *
     * @mbggenerated
     */
    private BigDecimal detailSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.FEE_TYPE
     *
     * @mbggenerated
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.PAY_TYPE
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.TRANSPORT_FEE
     *
     * @mbggenerated
     */
    private BigDecimal transportFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.GOOD_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal goodMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.T_FEE_STATUS
     *
     * @mbggenerated
     */
    private String tFeeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DELIVERY_ID
     *
     * @mbggenerated
     */
    private Long deliveryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DELIVERY_NO
     *
     * @mbggenerated
     */
    private String deliveryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.CARRIER_ID
     *
     * @mbggenerated
     */
    private Long carrierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.CARRIER_NAME
     *
     * @mbggenerated
     */
    private String carrierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.T_FUND_ID
     *
     * @mbggenerated
     */
    private Long tFundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.T_FUND_NO
     *
     * @mbggenerated
     */
    private String tFundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_PROVINCE
     *
     * @mbggenerated
     */
    private String dProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.D_COUNTY
     *
     * @mbggenerated
     */
    private String dCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_PROVINCE
     *
     * @mbggenerated
     */
    private String rProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.R_COUNTY
     *
     * @mbggenerated
     */
    private String rCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.SCAN_STATUS
     *
     * @mbggenerated
     */
    private String scanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.SCAN_TEL
     *
     * @mbggenerated
     */
    private String scanTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.V_ID
     *
     * @mbggenerated
     */
    private Long vId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.V_NO
     *
     * @mbggenerated
     */
    private String vNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.V_DRIVER_ID
     *
     * @mbggenerated
     */
    private Long vDriverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.V_SCAN_TEL
     *
     * @mbggenerated
     */
    private String vScanTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.V_DRIVER_NAME
     *
     * @mbggenerated
     */
    private String vDriverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.SIGN_TIME
     *
     * @mbggenerated
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DETAIL_TYPE
     *
     * @mbggenerated
     */
    private String detailType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.DETAIL_SIZE_LWH
     *
     * @mbggenerated
     */
    private String detailSizeLwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIR.TMS_WAYBILL.LAT_LNG
     *
     * @mbggenerated
     */
    private String latLng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.ID
     *
     * @return the value of MIR.TMS_WAYBILL.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.ID
     *
     * @param id the value for MIR.TMS_WAYBILL.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.NO
     *
     * @return the value of MIR.TMS_WAYBILL.NO
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.NO
     *
     * @param no the value for MIR.TMS_WAYBILL.NO
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.TICKET_NO
     *
     * @return the value of MIR.TMS_WAYBILL.TICKET_NO
     *
     * @mbggenerated
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.TICKET_NO
     *
     * @param ticketNo the value for MIR.TMS_WAYBILL.TICKET_NO
     *
     * @mbggenerated
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.SOURCE
     *
     * @return the value of MIR.TMS_WAYBILL.SOURCE
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.SOURCE
     *
     * @param source the value for MIR.TMS_WAYBILL.SOURCE
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.ORDER_NO
     *
     * @return the value of MIR.TMS_WAYBILL.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.ORDER_NO
     *
     * @param orderNo the value for MIR.TMS_WAYBILL.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.RECIPIENT
     *
     * @return the value of MIR.TMS_WAYBILL.RECIPIENT
     *
     * @mbggenerated
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.RECIPIENT
     *
     * @param recipient the value for MIR.TMS_WAYBILL.RECIPIENT
     *
     * @mbggenerated
     */
    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.RECEIVE_AT
     *
     * @return the value of MIR.TMS_WAYBILL.RECEIVE_AT
     *
     * @mbggenerated
     */
    public Date getReceiveAt() {
        return receiveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.RECEIVE_AT
     *
     * @param receiveAt the value for MIR.TMS_WAYBILL.RECEIVE_AT
     *
     * @mbggenerated
     */
    public void setReceiveAt(Date receiveAt) {
        this.receiveAt = receiveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DELIVERY_TYPE
     *
     * @return the value of MIR.TMS_WAYBILL.DELIVERY_TYPE
     *
     * @mbggenerated
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DELIVERY_TYPE
     *
     * @param deliveryType the value for MIR.TMS_WAYBILL.DELIVERY_TYPE
     *
     * @mbggenerated
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DELIVERY_DATE
     *
     * @return the value of MIR.TMS_WAYBILL.DELIVERY_DATE
     *
     * @mbggenerated
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DELIVERY_DATE
     *
     * @param deliveryDate the value for MIR.TMS_WAYBILL.DELIVERY_DATE
     *
     * @mbggenerated
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DELIVERY_TIME
     *
     * @return the value of MIR.TMS_WAYBILL.DELIVERY_TIME
     *
     * @mbggenerated
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DELIVERY_TIME
     *
     * @param deliveryTime the value for MIR.TMS_WAYBILL.DELIVERY_TIME
     *
     * @mbggenerated
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.REMARK
     *
     * @return the value of MIR.TMS_WAYBILL.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.REMARK
     *
     * @param remark the value for MIR.TMS_WAYBILL.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_ID
     *
     * @return the value of MIR.TMS_WAYBILL.D_ID
     *
     * @mbggenerated
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_ID
     *
     * @param dId the value for MIR.TMS_WAYBILL.D_ID
     *
     * @mbggenerated
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_NAME
     *
     * @return the value of MIR.TMS_WAYBILL.D_NAME
     *
     * @mbggenerated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_NAME
     *
     * @param dName the value for MIR.TMS_WAYBILL.D_NAME
     *
     * @mbggenerated
     */
    public void setdName(String dName) {
        this.dName = dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_CITY
     *
     * @return the value of MIR.TMS_WAYBILL.D_CITY
     *
     * @mbggenerated
     */
    public String getdCity() {
        return dCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_CITY
     *
     * @param dCity the value for MIR.TMS_WAYBILL.D_CITY
     *
     * @mbggenerated
     */
    public void setdCity(String dCity) {
        this.dCity = dCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_AREA
     *
     * @return the value of MIR.TMS_WAYBILL.D_AREA
     *
     * @mbggenerated
     */
    public String getdArea() {
        return dArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_AREA
     *
     * @param dArea the value for MIR.TMS_WAYBILL.D_AREA
     *
     * @mbggenerated
     */
    public void setdArea(String dArea) {
        this.dArea = dArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_POINT
     *
     * @return the value of MIR.TMS_WAYBILL.D_POINT
     *
     * @mbggenerated
     */
    public String getdPoint() {
        return dPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_POINT
     *
     * @param dPoint the value for MIR.TMS_WAYBILL.D_POINT
     *
     * @mbggenerated
     */
    public void setdPoint(String dPoint) {
        this.dPoint = dPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_TEL
     *
     * @return the value of MIR.TMS_WAYBILL.D_TEL
     *
     * @mbggenerated
     */
    public String getdTel() {
        return dTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_TEL
     *
     * @param dTel the value for MIR.TMS_WAYBILL.D_TEL
     *
     * @mbggenerated
     */
    public void setdTel(String dTel) {
        this.dTel = dTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_CONTACT
     *
     * @return the value of MIR.TMS_WAYBILL.D_CONTACT
     *
     * @mbggenerated
     */
    public String getdContact() {
        return dContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_CONTACT
     *
     * @param dContact the value for MIR.TMS_WAYBILL.D_CONTACT
     *
     * @mbggenerated
     */
    public void setdContact(String dContact) {
        this.dContact = dContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_ADDRESS
     *
     * @return the value of MIR.TMS_WAYBILL.D_ADDRESS
     *
     * @mbggenerated
     */
    public String getdAddress() {
        return dAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_ADDRESS
     *
     * @param dAddress the value for MIR.TMS_WAYBILL.D_ADDRESS
     *
     * @mbggenerated
     */
    public void setdAddress(String dAddress) {
        this.dAddress = dAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_ID
     *
     * @return the value of MIR.TMS_WAYBILL.R_ID
     *
     * @mbggenerated
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_ID
     *
     * @param rId the value for MIR.TMS_WAYBILL.R_ID
     *
     * @mbggenerated
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_NAME
     *
     * @return the value of MIR.TMS_WAYBILL.R_NAME
     *
     * @mbggenerated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_NAME
     *
     * @param rName the value for MIR.TMS_WAYBILL.R_NAME
     *
     * @mbggenerated
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_CITY
     *
     * @return the value of MIR.TMS_WAYBILL.R_CITY
     *
     * @mbggenerated
     */
    public String getrCity() {
        return rCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_CITY
     *
     * @param rCity the value for MIR.TMS_WAYBILL.R_CITY
     *
     * @mbggenerated
     */
    public void setrCity(String rCity) {
        this.rCity = rCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_AREA
     *
     * @return the value of MIR.TMS_WAYBILL.R_AREA
     *
     * @mbggenerated
     */
    public String getrArea() {
        return rArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_AREA
     *
     * @param rArea the value for MIR.TMS_WAYBILL.R_AREA
     *
     * @mbggenerated
     */
    public void setrArea(String rArea) {
        this.rArea = rArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_TEL
     *
     * @return the value of MIR.TMS_WAYBILL.R_TEL
     *
     * @mbggenerated
     */
    public String getrTel() {
        return rTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_TEL
     *
     * @param rTel the value for MIR.TMS_WAYBILL.R_TEL
     *
     * @mbggenerated
     */
    public void setrTel(String rTel) {
        this.rTel = rTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_CONTACT
     *
     * @return the value of MIR.TMS_WAYBILL.R_CONTACT
     *
     * @mbggenerated
     */
    public String getrContact() {
        return rContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_CONTACT
     *
     * @param rContact the value for MIR.TMS_WAYBILL.R_CONTACT
     *
     * @mbggenerated
     */
    public void setrContact(String rContact) {
        this.rContact = rContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_ADDRESS
     *
     * @return the value of MIR.TMS_WAYBILL.R_ADDRESS
     *
     * @mbggenerated
     */
    public String getrAddress() {
        return rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_ADDRESS
     *
     * @param rAddress the value for MIR.TMS_WAYBILL.R_ADDRESS
     *
     * @mbggenerated
     */
    public void setrAddress(String rAddress) {
        this.rAddress = rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DETAIL_NAME
     *
     * @return the value of MIR.TMS_WAYBILL.DETAIL_NAME
     *
     * @mbggenerated
     */
    public String getDetailName() {
        return detailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DETAIL_NAME
     *
     * @param detailName the value for MIR.TMS_WAYBILL.DETAIL_NAME
     *
     * @mbggenerated
     */
    public void setDetailName(String detailName) {
        this.detailName = detailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DETAIL_WEIGHT
     *
     * @return the value of MIR.TMS_WAYBILL.DETAIL_WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getDetailWeight() {
        return detailWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DETAIL_WEIGHT
     *
     * @param detailWeight the value for MIR.TMS_WAYBILL.DETAIL_WEIGHT
     *
     * @mbggenerated
     */
    public void setDetailWeight(BigDecimal detailWeight) {
        this.detailWeight = detailWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DETAIL_SIZE
     *
     * @return the value of MIR.TMS_WAYBILL.DETAIL_SIZE
     *
     * @mbggenerated
     */
    public BigDecimal getDetailSize() {
        return detailSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DETAIL_SIZE
     *
     * @param detailSize the value for MIR.TMS_WAYBILL.DETAIL_SIZE
     *
     * @mbggenerated
     */
    public void setDetailSize(BigDecimal detailSize) {
        this.detailSize = detailSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.FEE_TYPE
     *
     * @return the value of MIR.TMS_WAYBILL.FEE_TYPE
     *
     * @mbggenerated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.FEE_TYPE
     *
     * @param feeType the value for MIR.TMS_WAYBILL.FEE_TYPE
     *
     * @mbggenerated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.PAY_TYPE
     *
     * @return the value of MIR.TMS_WAYBILL.PAY_TYPE
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.PAY_TYPE
     *
     * @param payType the value for MIR.TMS_WAYBILL.PAY_TYPE
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.TRANSPORT_FEE
     *
     * @return the value of MIR.TMS_WAYBILL.TRANSPORT_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getTransportFee() {
        return transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.TRANSPORT_FEE
     *
     * @param transportFee the value for MIR.TMS_WAYBILL.TRANSPORT_FEE
     *
     * @mbggenerated
     */
    public void setTransportFee(BigDecimal transportFee) {
        this.transportFee = transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.GOOD_MONEY
     *
     * @return the value of MIR.TMS_WAYBILL.GOOD_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getGoodMoney() {
        return goodMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.GOOD_MONEY
     *
     * @param goodMoney the value for MIR.TMS_WAYBILL.GOOD_MONEY
     *
     * @mbggenerated
     */
    public void setGoodMoney(BigDecimal goodMoney) {
        this.goodMoney = goodMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.STATUS
     *
     * @return the value of MIR.TMS_WAYBILL.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.STATUS
     *
     * @param status the value for MIR.TMS_WAYBILL.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.CREATED_BY
     *
     * @return the value of MIR.TMS_WAYBILL.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.CREATED_BY
     *
     * @param createdBy the value for MIR.TMS_WAYBILL.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.CREATED_AT
     *
     * @return the value of MIR.TMS_WAYBILL.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.CREATED_AT
     *
     * @param createdAt the value for MIR.TMS_WAYBILL.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.UPDATED_BY
     *
     * @return the value of MIR.TMS_WAYBILL.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.UPDATED_BY
     *
     * @param updatedBy the value for MIR.TMS_WAYBILL.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.UPDATED_AT
     *
     * @return the value of MIR.TMS_WAYBILL.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.UPDATED_AT
     *
     * @param updatedAt the value for MIR.TMS_WAYBILL.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.T_FEE_STATUS
     *
     * @return the value of MIR.TMS_WAYBILL.T_FEE_STATUS
     *
     * @mbggenerated
     */
    public String gettFeeStatus() {
        return tFeeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.T_FEE_STATUS
     *
     * @param tFeeStatus the value for MIR.TMS_WAYBILL.T_FEE_STATUS
     *
     * @mbggenerated
     */
    public void settFeeStatus(String tFeeStatus) {
        this.tFeeStatus = tFeeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DELIVERY_ID
     *
     * @return the value of MIR.TMS_WAYBILL.DELIVERY_ID
     *
     * @mbggenerated
     */
    public Long getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DELIVERY_ID
     *
     * @param deliveryId the value for MIR.TMS_WAYBILL.DELIVERY_ID
     *
     * @mbggenerated
     */
    public void setDeliveryId(Long deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DELIVERY_NO
     *
     * @return the value of MIR.TMS_WAYBILL.DELIVERY_NO
     *
     * @mbggenerated
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DELIVERY_NO
     *
     * @param deliveryNo the value for MIR.TMS_WAYBILL.DELIVERY_NO
     *
     * @mbggenerated
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.CARRIER_ID
     *
     * @return the value of MIR.TMS_WAYBILL.CARRIER_ID
     *
     * @mbggenerated
     */
    public Long getCarrierId() {
        return carrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.CARRIER_ID
     *
     * @param carrierId the value for MIR.TMS_WAYBILL.CARRIER_ID
     *
     * @mbggenerated
     */
    public void setCarrierId(Long carrierId) {
        this.carrierId = carrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.CARRIER_NAME
     *
     * @return the value of MIR.TMS_WAYBILL.CARRIER_NAME
     *
     * @mbggenerated
     */
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.CARRIER_NAME
     *
     * @param carrierName the value for MIR.TMS_WAYBILL.CARRIER_NAME
     *
     * @mbggenerated
     */
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.T_FUND_ID
     *
     * @return the value of MIR.TMS_WAYBILL.T_FUND_ID
     *
     * @mbggenerated
     */
    public Long gettFundId() {
        return tFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.T_FUND_ID
     *
     * @param tFundId the value for MIR.TMS_WAYBILL.T_FUND_ID
     *
     * @mbggenerated
     */
    public void settFundId(Long tFundId) {
        this.tFundId = tFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.T_FUND_NO
     *
     * @return the value of MIR.TMS_WAYBILL.T_FUND_NO
     *
     * @mbggenerated
     */
    public String gettFundNo() {
        return tFundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.T_FUND_NO
     *
     * @param tFundNo the value for MIR.TMS_WAYBILL.T_FUND_NO
     *
     * @mbggenerated
     */
    public void settFundNo(String tFundNo) {
        this.tFundNo = tFundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_PROVINCE
     *
     * @return the value of MIR.TMS_WAYBILL.D_PROVINCE
     *
     * @mbggenerated
     */
    public String getdProvince() {
        return dProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_PROVINCE
     *
     * @param dProvince the value for MIR.TMS_WAYBILL.D_PROVINCE
     *
     * @mbggenerated
     */
    public void setdProvince(String dProvince) {
        this.dProvince = dProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.D_COUNTY
     *
     * @return the value of MIR.TMS_WAYBILL.D_COUNTY
     *
     * @mbggenerated
     */
    public String getdCounty() {
        return dCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.D_COUNTY
     *
     * @param dCounty the value for MIR.TMS_WAYBILL.D_COUNTY
     *
     * @mbggenerated
     */
    public void setdCounty(String dCounty) {
        this.dCounty = dCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_PROVINCE
     *
     * @return the value of MIR.TMS_WAYBILL.R_PROVINCE
     *
     * @mbggenerated
     */
    public String getrProvince() {
        return rProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_PROVINCE
     *
     * @param rProvince the value for MIR.TMS_WAYBILL.R_PROVINCE
     *
     * @mbggenerated
     */
    public void setrProvince(String rProvince) {
        this.rProvince = rProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.R_COUNTY
     *
     * @return the value of MIR.TMS_WAYBILL.R_COUNTY
     *
     * @mbggenerated
     */
    public String getrCounty() {
        return rCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.R_COUNTY
     *
     * @param rCounty the value for MIR.TMS_WAYBILL.R_COUNTY
     *
     * @mbggenerated
     */
    public void setrCounty(String rCounty) {
        this.rCounty = rCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.SCAN_STATUS
     *
     * @return the value of MIR.TMS_WAYBILL.SCAN_STATUS
     *
     * @mbggenerated
     */
    public String getScanStatus() {
        return scanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.SCAN_STATUS
     *
     * @param scanStatus the value for MIR.TMS_WAYBILL.SCAN_STATUS
     *
     * @mbggenerated
     */
    public void setScanStatus(String scanStatus) {
        this.scanStatus = scanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.SCAN_TEL
     *
     * @return the value of MIR.TMS_WAYBILL.SCAN_TEL
     *
     * @mbggenerated
     */
    public String getScanTel() {
        return scanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.SCAN_TEL
     *
     * @param scanTel the value for MIR.TMS_WAYBILL.SCAN_TEL
     *
     * @mbggenerated
     */
    public void setScanTel(String scanTel) {
        this.scanTel = scanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.V_ID
     *
     * @return the value of MIR.TMS_WAYBILL.V_ID
     *
     * @mbggenerated
     */
    public Long getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.V_ID
     *
     * @param vId the value for MIR.TMS_WAYBILL.V_ID
     *
     * @mbggenerated
     */
    public void setvId(Long vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.V_NO
     *
     * @return the value of MIR.TMS_WAYBILL.V_NO
     *
     * @mbggenerated
     */
    public String getvNo() {
        return vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.V_NO
     *
     * @param vNo the value for MIR.TMS_WAYBILL.V_NO
     *
     * @mbggenerated
     */
    public void setvNo(String vNo) {
        this.vNo = vNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.V_DRIVER_ID
     *
     * @return the value of MIR.TMS_WAYBILL.V_DRIVER_ID
     *
     * @mbggenerated
     */
    public Long getvDriverId() {
        return vDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.V_DRIVER_ID
     *
     * @param vDriverId the value for MIR.TMS_WAYBILL.V_DRIVER_ID
     *
     * @mbggenerated
     */
    public void setvDriverId(Long vDriverId) {
        this.vDriverId = vDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.V_SCAN_TEL
     *
     * @return the value of MIR.TMS_WAYBILL.V_SCAN_TEL
     *
     * @mbggenerated
     */
    public String getvScanTel() {
        return vScanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.V_SCAN_TEL
     *
     * @param vScanTel the value for MIR.TMS_WAYBILL.V_SCAN_TEL
     *
     * @mbggenerated
     */
    public void setvScanTel(String vScanTel) {
        this.vScanTel = vScanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.V_DRIVER_NAME
     *
     * @return the value of MIR.TMS_WAYBILL.V_DRIVER_NAME
     *
     * @mbggenerated
     */
    public String getvDriverName() {
        return vDriverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.V_DRIVER_NAME
     *
     * @param vDriverName the value for MIR.TMS_WAYBILL.V_DRIVER_NAME
     *
     * @mbggenerated
     */
    public void setvDriverName(String vDriverName) {
        this.vDriverName = vDriverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.SIGN_TIME
     *
     * @return the value of MIR.TMS_WAYBILL.SIGN_TIME
     *
     * @mbggenerated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.SIGN_TIME
     *
     * @param signTime the value for MIR.TMS_WAYBILL.SIGN_TIME
     *
     * @mbggenerated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DETAIL_TYPE
     *
     * @return the value of MIR.TMS_WAYBILL.DETAIL_TYPE
     *
     * @mbggenerated
     */
    public String getDetailType() {
        return detailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DETAIL_TYPE
     *
     * @param detailType the value for MIR.TMS_WAYBILL.DETAIL_TYPE
     *
     * @mbggenerated
     */
    public void setDetailType(String detailType) {
        this.detailType = detailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.DETAIL_SIZE_LWH
     *
     * @return the value of MIR.TMS_WAYBILL.DETAIL_SIZE_LWH
     *
     * @mbggenerated
     */
    public String getDetailSizeLwh() {
        return detailSizeLwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.DETAIL_SIZE_LWH
     *
     * @param detailSizeLwh the value for MIR.TMS_WAYBILL.DETAIL_SIZE_LWH
     *
     * @mbggenerated
     */
    public void setDetailSizeLwh(String detailSizeLwh) {
        this.detailSizeLwh = detailSizeLwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIR.TMS_WAYBILL.LAT_LNG
     *
     * @return the value of MIR.TMS_WAYBILL.LAT_LNG
     *
     * @mbggenerated
     */
    public String getLatLng() {
        return latLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIR.TMS_WAYBILL.LAT_LNG
     *
     * @param latLng the value for MIR.TMS_WAYBILL.LAT_LNG
     *
     * @mbggenerated
     */
    public void setLatLng(String latLng) {
        this.latLng = latLng;
    }
}