package com.hoperun.framework.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-03T10:08:47.900+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.hoperun.shinho.sms.SendSMS")
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.hoperun.shinho.sms.SendSMSResponse")
    public java.lang.String sendSMS(
        @WebParam(name = "phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "s_txt", targetNamespace = "http://tempuri.org/")
        java.lang.String sTxt
    );

    @WebResult(name = "send_YX_SMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "send_YX_SMS", targetNamespace = "http://tempuri.org/", className = "com.hoperun.shinho.sms.SendYXSMS")
    @WebMethod(operationName = "send_YX_SMS", action = "http://tempuri.org/send_YX_SMS")
    @ResponseWrapper(localName = "send_YX_SMSResponse", targetNamespace = "http://tempuri.org/", className = "com.hoperun.shinho.sms.SendYXSMSResponse")
    public java.lang.String sendYXSMS(
        @WebParam(name = "phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "s_txt", targetNamespace = "http://tempuri.org/")
        java.lang.String sTxt
    );
}
