
package com.hoperun.framework.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-03T10:08:47.770+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class Service1Soap_Service1Soap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private Service1Soap_Service1Soap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        Service1Soap port = ss.getService1Soap12();  
        
        {
        System.out.println("Invoking sendSMS...");
        java.lang.String _sendSMS_phone = "";
        java.lang.String _sendSMS_sTxt = "";
        java.lang.String _sendSMS__return = port.sendSMS(_sendSMS_phone, _sendSMS_sTxt);
        System.out.println("sendSMS.result=" + _sendSMS__return);


        }
        {
        System.out.println("Invoking sendYXSMS...");
        java.lang.String _sendYXSMS_phone = "";
        java.lang.String _sendYXSMS_sTxt = "";
        java.lang.String _sendYXSMS__return = port.sendYXSMS(_sendYXSMS_phone, _sendYXSMS_sTxt);
        System.out.println("sendYXSMS.result=" + _sendYXSMS__return);


        }

        System.exit(0);
    }

}
