package com.hoperun.framework.sms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-03T10:08:47.950+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "Service1", 
                  //wsdlLocation = "http://www.shinho.com.cn/sendsms/service1.asmx?WSDL",
                  wsdlLocation = "http://ms.liangrong-bm.cn/service1.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class Service1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Service1");
    public final static QName Service1Soap12 = new QName("http://tempuri.org/", "Service1Soap12");
    public final static QName Service1Soap = new QName("http://tempuri.org/", "Service1Soap");
    static {
        URL url = null;
        try {
            //url = new URL("http://www.shinho.com.cn/sendsms/service1.asmx?WSDL");
        	url = new URL("http://ms.liangrong-bm.cn/service1.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     //"Can not initialize the default wsdl from {0}", "http://www.shinho.com.cn/sendsms/service1.asmx?WSDL");
                	"Can not initialize the default wsdl from {0}", "http://ms.liangrong-bm.cn/service1.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Service1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Service1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Service1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Service1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap12")
    public Service1Soap getService1Soap12() {
        return super.getPort(Service1Soap12, Service1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap12")
    public Service1Soap getService1Soap12(WebServiceFeature... features) {
        return super.getPort(Service1Soap12, Service1Soap.class, features);
    }


    /**
     *
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap")
    public Service1Soap getService1Soap() {
        return super.getPort(Service1Soap, Service1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap")
    public Service1Soap getService1Soap(WebServiceFeature... features) {
        return super.getPort(Service1Soap, Service1Soap.class, features);
    }

}
